name: Test Repo Construction

on:
  pull_request:
    branches:
      - master

jobs:
  test-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip install cookiecutter
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
        rm -Rf python_workflow/.github/workflows/
    - name: Publish Repo
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: ${{ github.head_ref }} # The branch the action should deploy from.
        BRANCH: 'test-build' # The branch the action should deploy to.
        FOLDER: python_workflow/ # The folder the action should deploy
        CLEAN: true
